// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjNqIY8CksrxqvnesNpbvu-z6Tz26N0rQ',
    appId: '1:512993661420:web:cdab5dd05d5d6d786030c9',
    messagingSenderId: '512993661420',
    projectId: 'gapfix',
    authDomain: 'gapfix.firebaseapp.com',
    databaseURL: 'https://gapfix-default-rtdb.firebaseio.com',
    storageBucket: 'gapfix.firebasestorage.app',
    measurementId: 'G-N99S42VNNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxq9aqvkQ04w-nUpxiwguh_4OQ4MtVb6I',
    appId: '1:512993661420:android:27a234d130f5b22b6030c9',
    messagingSenderId: '512993661420',
    projectId: 'gapfix',
    databaseURL: 'https://gapfix-default-rtdb.firebaseio.com',
    storageBucket: 'gapfix.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA6M2Ysu93KtcKtThSPapYAisiZpNPDtA',
    appId: '1:512993661420:ios:135b8fc6fdebe72e6030c9',
    messagingSenderId: '512993661420',
    projectId: 'gapfix',
    databaseURL: 'https://gapfix-default-rtdb.firebaseio.com',
    storageBucket: 'gapfix.firebasestorage.app',
    androidClientId: '512993661420-83j5h0q06d1sg69309rval8dngb2ptbc.apps.googleusercontent.com',
    iosClientId: '512993661420-ona9oa31jomo2p6hgt2m5i55dte4q2m0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gapfix.gapfix',
  );
}
